kind: pipeline
type: docker
name: deploy-image

steps:
  - name: test-build
    image: node:16-alpine
    volumes:
    - name: cache
      path: /drone/src/node_modules
    commands:
      - yarn install
      - yarn run prisma:generate
      - yarn lint
      - yarn test-build

  - name: build docker file and push to docker hub
    image: plugins/docker
    settings:
      repo: guusvanmeerveld/portfolio
      tags: latest
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
        
volumes:
  - name: cache
    host:
      path: /tmp/drone/cache/node_modules