kind: pipeline
type: docker
name: deploy-image

steps:
  - name: test-build
    image: node:16-alpine
    commands:
      - yarn install
      - yarn lint
      - yarn build

  - name: build docker file and push to docker hub
    image: plugins/docker
    pull: never
    settings:
      repo: guusvanmeerveld/portfolio
      tags: latest
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password