name: Auto-merge dependabot

on:
  pull_request:

permissions:
  pull-requests: write

jobs:
  auto-merge:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        name: Checkout

      - uses: ahmadnassri/action-dependabot-auto-merge@v2
        name: Auto merge
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
