name: deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup checkout
        uses: actions/checkout@v2

      - name: Setup NodeJS v20
        uses: actions/setup-node@v1
        with:
          node-version: 20

      - name: Install Dependencies
        run: yarn install

      - name: ESlint check
        run: yarn lint

      - name: Build static site
        run: yarn build

      - name: Upload GitHub Pages artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: out/

  publish-pages:
    needs: build

    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}

    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source

    steps:
      - name: Deploy artifact to pages
        id: deployment
        uses: actions/deploy-pages@v4

  # docker:
  #   runs-on: ubuntu-latest
  #   needs: typescript
  #   steps:
  #     - name: Set up QEMU
  #       uses: docker/setup-qemu-action@v1

  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v1

  #     - name: Login to DockerHub
  #       uses: docker/login-action@v1
  #       with:
  #         username: ${{ secrets.DOCKERHUB_USERNAME }}
  #         password: ${{ secrets.DOCKERHUB_TOKEN }}

  #     - name: Build Dockerfile and push
  #       id: docker_build
  #       uses: docker/build-push-action@v2
  #       with:
  #         push: true
  #         tags: guusvanmeerveld/portfolio:latest

  #     - name: Image digest
  #       run: echo ${{ steps.docker_build.outputs.digest }}
