name: "Deploy website"

on:
  push:
    branches:
      - main
    paths:
      - src/**
      - package.json
      - yarn.lock
      - tsconfig.*
      - vite.config.ts
      - .env
      - index.html
      - public

jobs:
  deploy_to_pages:
    name: Build pages
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"
          cache: "yarn"

      - name: Install NPM dependencies
        run: yarn install

      - name: Build client
        run: yarn run build

      - name: Deploy to pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          cname: guusvanmeerveld.dev
